# Generated by Django 4.2 on 2025-11-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('publication_year', models.IntegerField(verbose_name='Año de publicación')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-publication_year', 'title'],
            },
        ),
    ]
